create table public.cbx_torneios (
  id integer generated by default as identity not null,
  cbx_titulo text null,
  cbx_id text null,
  cbx_organizador text null,
  cbx_local text null,
  cbx_periodo text null,
  cbx_observacao text null,
  cbx_regulamento text null,
  cbx_situacao text null,
  cbx_ritmo text null,
  cbx_rating text null,
  cbx_jogadores text null,
  cbx_jogadores_fide text null,
  created_at timestamp with time zone not null default now(),
  constraint CBX_tournaments_pkey primary key (id),
  constraint cbx_tournaments_cbx_id_key unique (cbx_id)
) TABLESPACE pg_default;


create table public.cbx_jogadores (
  id integer generated by default as identity not null,
  cbx_id text null,
  cbx_fide_id text null,
  cbx_nome text null,
  cbx_nascimento text null,
  cbx_uf text null,
  cbx_classico text null,
  cbx_rapido text null,
  cbx_blitz text null,
  created_at timestamp with time zone not null default now(),
  constraint cbx_jogadores_pkey primary key (id),
  constraint cbx_jogadores_cbx_id_key unique (cbx_id)
) TABLESPACE pg_default;