create table public.cbx_comunicados (
  id smallint generated by default as identity not null,
  titulo text null,
  link text null,
  data_hora text null,
  created_at timestamp with time zone not null default now(),
  constraint cbx_comunicados_pkey primary key (id),
  constraint cbx_comunicados_cbx_link_key unique (link)
) TABLESPACE pg_default;


create table public.cbx_jogadores (
  id integer generated by default as identity not null,
  cbx_id text null,
  fide_id text null,
  nome text null,
  nascimento text null,
  uf text null,
  classico text null,
  rapido text null,
  blitz text null,
  created_at timestamp with time zone not null default now(),
  constraint cbx_jogadores_pkey primary key (id),
  constraint cbx_jogadores_cbx_id_key unique (cbx_id)
) TABLESPACE pg_default;


create table public.cbx_noticias (
  id smallint generated by default as identity not null,
  titulo text null,
  link text null,
  data_hora text null,
  created_at timestamp with time zone not null default now(),
  constraint cbx_noticias_pkey primary key (id),
  constraint cbx_noticias_cbx_link_key unique (link)
) TABLESPACE pg_default;


create table public.cbx_torneios (
  id integer generated by default as identity not null,
  titulo text null,
  cbx_id text null,
  organizador text null,
  local text null,
  periodo text null,
  observacao text null,
  regulamento text null,
  situacao text null,
  ritmo text null,
  rating text null,
  jogadores text null,
  jogadores_fide text null,
  created_at timestamp with time zone not null default now(),
  constraint CBX_tournaments_pkey primary key (id),
  constraint cbx_tournaments_cbx_id_key unique (cbx_id)
) TABLESPACE pg_default;


create table public.fide_tournaments (
  id integer generated by default as identity not null,
  name text null,
  city text null,
  s text null,
  start text null,
  rcvd text null,
  created_at timestamp with time zone not null default now(),
  country text null,
  period text null,
  fide_id text null,
  -- link_information text null,
  -- link_event text null,
  constraint fide_tournaments_pkey primary key (id),
  constraint fide_tournaments_fide_id_key unique (fide_id)
) TABLESPACE pg_default;
-- https://ratings.fide.com/tournament_information.phtml?event=34900
-- https://ratings.fide.com/report.phtml?event=15066